plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = '0.1.1'
group = 'fr.emattera.capsulecorp'

base {
    archivesName = 'capsulecorp'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.228'

    runs {
        client {
            client()
        }

        server {
            server()
        }
    }

    mods {
        capsulecorp {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    mavenCentral()

    maven {
        url "https://cursemaven.com"
    }

    maven {
        name = "BlameJared Maven"
        url = "https://maven.blamejared.com"
    }

    maven {
        name = "Fuzs Maven"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven"
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "RyanHCode Maven"
                url = "https://maven.ryanhcode.dev/releases"
            }
        }

        filter {
            includeGroup("dev.ryanhcode.sable")
            includeGroup("dev.ryanhcode.sable-companion")
        }
    }
}

dependencies {
    api("dev.ryanhcode.sable:sable-common-1.21.1:${sable_version}")

    compileOnly "curse.maven:create-328085:7963363"
    runtimeOnly "curse.maven:create-328085:7963363"

    compileOnly "curse.maven:sableschemapi-1526951:8071476"
    runtimeOnly "curse.maven:sableschemapi-1526951:8071476"

    compileOnly "curse.maven:sable-1312371:8007005"
    runtimeOnly "curse.maven:sable-1312371:8007005"

    compileOnly "curse.maven:ldlib2-626676:8108634"
    runtimeOnly "curse.maven:ldlib2-626676:8108634"

    jarJar(api("dev.ryanhcode.sable-companion:sable-companion-common-1.21.1:[1.6.0,)")) {
        version {
            prefer "1.6.0"
        }
    }
}