pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = "https://maven.neoforged.net/releases" }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        mavenCentral()
        maven { url = "https://maven.neoforged.net/releases" }
        maven { url = "https://maven.createmod.net" }
        maven { url = "https://maven.ryanhcode.dev/releases" }
    }
}

rootProject.name = "create-capsule-corp"